"""
config.py — golf-domain config values per spec v3 §10.

PR-7a ships these as STARTING ESTIMATES. PR-7b's sweep harness
will overwrite ANATOMICAL_OFFSETS with values that minimize mean
pixel error against Jason's 15-sample ground truth. Until then,
these defaults produce a reasonable (not optimal) corrected
timeline that's good enough for offline inspection.

Per PR-7_REVIEW_RESPONSE.md Constraint 2:
  - face_on values: starting estimates for sweep optimization
  - down_the_line values: conservative; if sweep can't converge on
    just 5 DTL samples, view_aware.py applies a 1.10× multiplier
    fallback to face_on values

Per PR-7_REVIEW_RESPONSE.md Constraint 6:
  - PHASE_CONFIG locks phase-aware smoothing. temporal_smoother.py
    refuses calls without a phase arg, so no uniform-alpha hack is
    syntactically expressible.
"""
from __future__ import annotations


# Per-view anatomical offset coefficients. Each value is the fraction
# of the (joint → torso center) vector applied as inward correction.
# Tuned in PR-7b.
# === BEGIN FITTED ANATOMICAL_OFFSETS (auto-generated by fit_offsets_from_gt.py) ===

# Per-joint 3D offset vectors for fitted joints (shoulder/hip/neck)
# + legacy group-keyed scalars for non-fitted (knee/ankle/wrist).
# Engine dispatches by value type: list[3] → mode A vector; scalar → mode B.
ANATOMICAL_OFFSETS: dict[str, dict] = {
    'face_on': {
        'left_hip'              : {
            'finish'      : [-0.04941, +0.00000, -0.03241],
            'impact'      : [-0.01353, +0.00000, -0.01982],
            'setup'       : [-0.00778, +0.00000, -0.03078],
            'top'         : [-0.00690, +0.00000, -0.04020],
            'transition'  : [-0.00340, +0.00000, -0.03601],
            'backswing'   : [-0.00734, +0.00000, -0.03549],
            'downswing'   : [-0.00847, +0.00000, -0.02792],
        },
        'left_shoulder'         : {
            'finish'      : [-0.02401, +0.05041, +0.01981],
            'impact'      : [+0.00392, +0.07634, +0.06544],
            'setup'       : [+0.03763, +0.04381, +0.04674],
            'top'         : [+0.03554, +0.03978, +0.04317],
            'transition'  : [+0.02426, +0.04923, +0.05229],
            'backswing'   : [+0.03658, +0.04179, +0.04495],
            'downswing'   : [+0.01409, +0.06279, +0.05887],
        },
        'neck'                  : {
            'finish'      : [+0.02908, +0.20940, +0.10612],
            'impact'      : [-0.04860, +0.22795, +0.20087],
            'setup'       : [-0.04309, +0.18035, +0.19228],
            'top'         : [-0.04928, +0.18605, +0.20179],
            'transition'  : [-0.04943, +0.19305, +0.20539],
            'backswing'   : [-0.04619, +0.18320, +0.19704],
            'downswing'   : [-0.04902, +0.21050, +0.20313],
        },
        'right_hip'             : {
            'finish'      : [-0.11922, +0.00000, +0.00839],
            'impact'      : [-0.05194, +0.00000, -0.02853],
            'setup'       : [-0.04897, +0.00000, -0.02381],
            'top'         : [-0.06385, +0.00000, -0.02564],
            'transition'  : [-0.08146, +0.00000, -0.03405],
            'backswing'   : [-0.05641, +0.00000, -0.02473],
            'downswing'   : [-0.06670, +0.00000, -0.03129],
        },
        'right_shoulder'        : {
            'finish'      : [-0.07104, +0.05841, +0.02737],
            'impact'      : [-0.07600, +0.05259, +0.04682],
            'setup'       : [-0.14093, +0.04618, +0.04925],
            'top'         : [-0.15261, +0.04533, +0.04917],
            'transition'  : [-0.15711, +0.04516, +0.04817],
            'backswing'   : [-0.14677, +0.04576, +0.04921],
            'downswing'   : [-0.11655, +0.04888, +0.04749],
        },
        'knee_inward'           : +0.0500,
        'ankle_inward'          : +0.0300,
        'wrist_inward'          : +0.0000,
    },
    'down_the_line': {
        'left_hip'              : {
            'finish'      : [-0.00129, +0.00000, +0.00512],
            'impact'      : [-0.01609, +0.00000, +0.00501],
            'setup'       : [+0.01314, +0.00000, +0.00382],
            'top'         : [-0.09227, +0.00000, +0.00000],
            'transition'  : [-0.01728, +0.00000, -0.00057],
            'backswing'   : [+0.01314, +0.00000, +0.00382],
            'downswing'   : [-0.01668, +0.00000, +0.00222],
        },
        'left_shoulder'         : {
            'finish'      : [+0.00227, +0.07608, -0.01214],
            'impact'      : [-0.01667, +0.07026, -0.01289],
            'setup'       : [+0.05005, +0.03538, -0.00371],
            'top'         : [+0.01725, +0.05179, -0.00008],
            'transition'  : [-0.02107, +0.09412, -0.01765],
            'backswing'   : [+0.03365, +0.04358, -0.00190],
            'downswing'   : [-0.01887, +0.08219, -0.01527],
        },
        'neck'                  : {
            'finish'      : [-0.01826, +0.32432, -0.05176],
            'impact'      : [+0.00818, +0.32812, -0.06020],
            'setup'       : [+0.10903, +0.21020, -0.02202],
            'top'         : [+0.06834, +0.31362, -0.00051],
            'transition'  : [-0.07149, +0.29769, -0.05584],
            'backswing'   : [+0.08868, +0.26191, -0.01127],
            'downswing'   : [-0.03166, +0.31290, -0.05802],
        },
        'right_hip'             : {
            'finish'      : [+0.04465, +0.00000, -0.00001],
            'impact'      : [+0.05287, +0.00000, +0.00323],
            'setup'       : [+0.01995, +0.00000, -0.00165],
            'top'         : [+0.08102, +0.00000, +0.00003],
            'transition'  : [+0.03813, +0.00000, -0.00211],
            'backswing'   : [+0.01995, +0.00000, -0.00165],
            'downswing'   : [+0.01995, +0.00000, -0.00165],
        },
        'right_shoulder'        : {
            'finish'      : [+0.05281, +0.10243, -0.01635],
            'impact'      : [+0.05470, +0.10322, -0.01894],
            'setup'       : [+0.05770, +0.06989, -0.00732],
            'top'         : [+0.13301, +0.07683, -0.00012],
            'transition'  : [+0.01598, +0.11349, -0.02129],
            'backswing'   : [+0.09535, +0.07336, -0.00372],
            'downswing'   : [+0.03534, +0.10836, -0.02012],
        },
        'knee_inward'           : +0.0500,
        'ankle_inward'          : +0.0300,
        'wrist_inward'          : +0.0000,
    },
}

# Pre-Option-2 hardcoded scalar fallback. Preserved for reproducibility
# and as a guard against config-corruption — engine still supports the
# scalar inward-pull math (mode B) if a future hot-fix needs to revert.
ANATOMICAL_OFFSETS_FALLBACK: dict[str, dict[str, float]] = {
    'face_on':       {'shoulder_inward': 0.14, 'hip_inward': 0.16, 'head_inward': 0.08, 'knee_inward': 0.05, 'ankle_inward': 0.03, 'wrist_inward': 0.0},
    'down_the_line': {'shoulder_inward': 0.18, 'hip_inward': 0.2, 'head_inward': 0.08, 'knee_inward': 0.05, 'ankle_inward': 0.03, 'wrist_inward': 0.0},
}

# === END FITTED ANATOMICAL_OFFSETS ===

# Phase-aware smoothing + outlier rejection thresholds.
#
# alpha:         EMA weight on current frame (1-alpha goes to previous).
#                Smaller = heavier smoothing (more lag, less jitter).
# outlier_ratio: a frame-to-frame motion exceeding
#                outlier_ratio × baseline_shoulder_width is flagged as
#                outlier and the previous smoothed value is reused.
#
# Per Constraint 6: code-review hard-blocks any temporal_smoother call
# without a phase arg. The dict shape (one entry per phase) is the
# enforcement vector.
PHASE_CONFIG: dict[str, dict[str, float]] = {
    "setup":      {"alpha": 0.05, "outlier_ratio": 0.10},  # PR-7a.1 Fix 1: very heavy smoothing — near-frozen for static setup
    "backswing":  {"alpha": 0.30, "outlier_ratio": 0.25},  # medium
    "top":        {"alpha": 0.30, "outlier_ratio": 0.35},  # medium (brief)
    "transition": {"alpha": 0.30, "outlier_ratio": 0.35},  # medium
    "downswing":  {"alpha": 0.40, "outlier_ratio": 0.40},  # light — fast motion
    "impact":     {"alpha": 0.40, "outlier_ratio": 0.40},  # light — fastest
    "finish":     {"alpha": 0.30, "outlier_ratio": 0.30},  # medium (decel)
}


# Shared smoothing knobs not phase-keyed.
SMOOTHING_COMMON: dict[str, float] = {
    "alpha_low_conf":         0.10,
    "confidence_threshold":   0.65,
    "velocity_outlier_ratio": 0.25,
    "bidirectional_enabled":  False,   # PR-7a leaves bidirectional off
                                        # (offline pipeline can afford it,
                                        #  but PR-7c production needs causal
                                        #  for stream rendering; keep parity)
}


# L/R identity stability tunables.
LR_STABILITY: dict[str, float | tuple] = {
    "swap_threshold_ratio": 0.70,
    "phase_strict_swap": ("setup", "backswing"),
}
